//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_Products_MVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Product_detail
    {
        public int id { get; set; }
        [Display(Name = "Product Name")]
        public Nullable<int> product_id { get; set; }
        [Display(Name = "Product Name")]
        public string product_name { get; set; }
        [Display(Name = "Vendor Name")]
        public string vendor { get; set; }
        [Display(Name = "Purchased Date")]
        public Nullable<System.DateTime> purchase_date { get; set; }
        [Display(Name = "Purchased Price")]
        public Nullable<decimal> purchase_price { get; set; }
        [Display(Name = "Count")]
        public Nullable<decimal> total_count { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
